
[testing]
example_file = "ready_blast_outputs/Escherichia_coli_536-vs-Escherichia_coli_536.bl"

[parsing]
separator = "\t"
columns = [
    "query id", "subject id", "% identity", "alignment length", 
    "mismatches", "gap opens", "gaps", "q. start", "q. end", 
    "s. start", "s. end", "e-value", "bit score", 
    "query length", "subject length"
]
criteria.names = [
    "% identity", "alignment length", 
    "mismatches", "gap opens", "gaps", "q. start", "q. end", 
    "s. start", "s. end", "e-value", "bit score", 
    "query length", "subject length"
]
criteria.is_int = [
    false, true,
    true, true, true, true, true,
    true, true, false, false, 
    true, true
]

[parsing.file]
extension = ".bl"
strain_sep = "-vs-"

[parsing.threshold_greater]
coverage = true
log_bit_score = true
"% identity" = true
log_e_value = false